package pe.brice.smsreplay.data.model

/**
 * Data layer model for pending SMS in offline queue
 * Stored in Room Database
 */
data class PendingSmsData(
    val id: Long = 0, // Auto-generated by Room
    val sender: String,
    val body: String,
    val timestamp: Long,
    val retryCount: Int = 0,
    val maxRetries: Int = 3
) {
    /**
     * Check if retry limit exceeded
     */
    fun shouldRetry(): Boolean {
        return retryCount < maxRetries
    }

    /**
     * Increment retry count
     */
    fun incrementRetry(): PendingSmsData {
        return copy(retryCount = retryCount + 1)
    }

    /**
     * Format timestamp for display
     */
    fun getFormattedTime(): String {
        val dateFormat = java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss", java.util.Locale.getDefault())
        return dateFormat.format(java.util.Date(timestamp))
    }
}
